[project]
name = "wkthompson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter-book>=2.0.2",
    "pip>=25.3",
]
